-d C:\Users\Das\Dropbox\Obsidian\Fisica\tmp\VHDL-ART\Practica6TwosComplement\DesGenerate-Version\pjt\impl\gwsynthesis\pjt.vg
-p GW1NZ-1-QFN48-6
-pn GW1NZ-LV1QN48C6/I5
-cfg C:\Users\Das\Dropbox\Obsidian\Fisica\tmp\VHDL-ART\Practica6TwosComplement\DesGenerate-Version\pjt\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 10
