-d C:\Users\dasre\Documents\Knowledge-db\ghFiles\HDL-ART\Examen3TrapecioMetodos\SPI\impl\gwsynthesis\SPI.vg
-p GW1NZ-1-QFN48-6
-pn GW1NZ-LV1QN48C6/I5
-cst C:\Users\dasre\Documents\Knowledge-db\ghFiles\HDL-ART\Examen3TrapecioMetodos\SPI\src\SPI.cst
-cfg C:\Users\dasre\Documents\Knowledge-db\ghFiles\HDL-ART\Examen3TrapecioMetodos\SPI\impl\pnr\device.cfg
-gao_crc 0111100101001011
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 10
-global_freq 50.000
-rtl_gao
